# Generated by Django 3.1.3 on 2021-12-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='seqNo',
            field=models.IntegerField(default=0),
        ),
    ]
